/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateSourceRequest,
  HTTPValidationError,
  MetadataResponse,
  UpdateSourceRequest,
  VersionResponse,
} from '../models/index';
import {
    CreateSourceRequestFromJSON,
    CreateSourceRequestToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    MetadataResponseFromJSON,
    MetadataResponseToJSON,
    UpdateSourceRequestFromJSON,
    UpdateSourceRequestToJSON,
    VersionResponseFromJSON,
    VersionResponseToJSON,
} from '../models/index';

export interface ActivateVersionBronzeSourceIdVersionsVersionPatchRequest {
    sourceId: number;
    version: number;
}

export interface CreateSourceBronzePostRequest {
    createSourceRequest: CreateSourceRequest;
}

export interface DeleteSourceBronzeSourceIdDeleteRequest {
    sourceId: number;
}

export interface DeleteVersionBronzeSourceIdVersionsVersionDeleteRequest {
    sourceId: number;
    version: number;
}

export interface DownloadVersionBronzeSourceIdVersionsVersionGetRequest {
    sourceId: number;
    version: number;
}

export interface GetSourceBronzeSourceIdGetRequest {
    sourceId: number;
}

export interface ListVersionsBronzeSourceIdVersionsGetRequest {
    sourceId: number;
}

export interface UpdateSourceBronzeSourceIdPatchRequest {
    sourceId: number;
    updateSourceRequest: UpdateSourceRequest;
}

export interface UploadVersionBronzeSourceIdVersionsPostRequest {
    sourceId: number;
    file: string;
}

/**
 * 
 */
export class APIEndpointsForInteractingWithTheBronzeLayerApi extends runtime.BaseAPI {

    /**
     * Activate Version
     */
    async activateVersionBronzeSourceIdVersionsVersionPatchRaw(requestParameters: ActivateVersionBronzeSourceIdVersionsVersionPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['sourceId'] == null) {
            throw new runtime.RequiredError(
                'sourceId',
                'Required parameter "sourceId" was null or undefined when calling activateVersionBronzeSourceIdVersionsVersionPatch().'
            );
        }

        if (requestParameters['version'] == null) {
            throw new runtime.RequiredError(
                'version',
                'Required parameter "version" was null or undefined when calling activateVersionBronzeSourceIdVersionsVersionPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/bronze/{source_id}/versions/{version}`;
        urlPath = urlPath.replace(`{${"source_id"}}`, encodeURIComponent(String(requestParameters['sourceId'])));
        urlPath = urlPath.replace(`{${"version"}}`, encodeURIComponent(String(requestParameters['version'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Activate Version
     */
    async activateVersionBronzeSourceIdVersionsVersionPatch(requestParameters: ActivateVersionBronzeSourceIdVersionsVersionPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.activateVersionBronzeSourceIdVersionsVersionPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create Source
     */
    async createSourceBronzePostRaw(requestParameters: CreateSourceBronzePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['createSourceRequest'] == null) {
            throw new runtime.RequiredError(
                'createSourceRequest',
                'Required parameter "createSourceRequest" was null or undefined when calling createSourceBronzePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/bronze/`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateSourceRequestToJSON(requestParameters['createSourceRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Create Source
     */
    async createSourceBronzePost(requestParameters: CreateSourceBronzePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.createSourceBronzePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Source
     */
    async deleteSourceBronzeSourceIdDeleteRaw(requestParameters: DeleteSourceBronzeSourceIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['sourceId'] == null) {
            throw new runtime.RequiredError(
                'sourceId',
                'Required parameter "sourceId" was null or undefined when calling deleteSourceBronzeSourceIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/bronze/{source_id}`;
        urlPath = urlPath.replace(`{${"source_id"}}`, encodeURIComponent(String(requestParameters['sourceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete Source
     */
    async deleteSourceBronzeSourceIdDelete(requestParameters: DeleteSourceBronzeSourceIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.deleteSourceBronzeSourceIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Version
     */
    async deleteVersionBronzeSourceIdVersionsVersionDeleteRaw(requestParameters: DeleteVersionBronzeSourceIdVersionsVersionDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['sourceId'] == null) {
            throw new runtime.RequiredError(
                'sourceId',
                'Required parameter "sourceId" was null or undefined when calling deleteVersionBronzeSourceIdVersionsVersionDelete().'
            );
        }

        if (requestParameters['version'] == null) {
            throw new runtime.RequiredError(
                'version',
                'Required parameter "version" was null or undefined when calling deleteVersionBronzeSourceIdVersionsVersionDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/bronze/{source_id}/versions/{version}`;
        urlPath = urlPath.replace(`{${"source_id"}}`, encodeURIComponent(String(requestParameters['sourceId'])));
        urlPath = urlPath.replace(`{${"version"}}`, encodeURIComponent(String(requestParameters['version'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete Version
     */
    async deleteVersionBronzeSourceIdVersionsVersionDelete(requestParameters: DeleteVersionBronzeSourceIdVersionsVersionDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.deleteVersionBronzeSourceIdVersionsVersionDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Download Version
     */
    async downloadVersionBronzeSourceIdVersionsVersionGetRaw(requestParameters: DownloadVersionBronzeSourceIdVersionsVersionGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['sourceId'] == null) {
            throw new runtime.RequiredError(
                'sourceId',
                'Required parameter "sourceId" was null or undefined when calling downloadVersionBronzeSourceIdVersionsVersionGet().'
            );
        }

        if (requestParameters['version'] == null) {
            throw new runtime.RequiredError(
                'version',
                'Required parameter "version" was null or undefined when calling downloadVersionBronzeSourceIdVersionsVersionGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/bronze/{source_id}/versions/{version}`;
        urlPath = urlPath.replace(`{${"source_id"}}`, encodeURIComponent(String(requestParameters['sourceId'])));
        urlPath = urlPath.replace(`{${"version"}}`, encodeURIComponent(String(requestParameters['version'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Download Version
     */
    async downloadVersionBronzeSourceIdVersionsVersionGet(requestParameters: DownloadVersionBronzeSourceIdVersionsVersionGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.downloadVersionBronzeSourceIdVersionsVersionGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Source
     */
    async getSourceBronzeSourceIdGetRaw(requestParameters: GetSourceBronzeSourceIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MetadataResponse>> {
        if (requestParameters['sourceId'] == null) {
            throw new runtime.RequiredError(
                'sourceId',
                'Required parameter "sourceId" was null or undefined when calling getSourceBronzeSourceIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/bronze/{source_id}`;
        urlPath = urlPath.replace(`{${"source_id"}}`, encodeURIComponent(String(requestParameters['sourceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MetadataResponseFromJSON(jsonValue));
    }

    /**
     * Get Source
     */
    async getSourceBronzeSourceIdGet(requestParameters: GetSourceBronzeSourceIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MetadataResponse> {
        const response = await this.getSourceBronzeSourceIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Sources
     */
    async listSourcesBronzeGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<MetadataResponse>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/bronze/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MetadataResponseFromJSON));
    }

    /**
     * List Sources
     */
    async listSourcesBronzeGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MetadataResponse>> {
        const response = await this.listSourcesBronzeGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * List Versions
     */
    async listVersionsBronzeSourceIdVersionsGetRaw(requestParameters: ListVersionsBronzeSourceIdVersionsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<VersionResponse>>> {
        if (requestParameters['sourceId'] == null) {
            throw new runtime.RequiredError(
                'sourceId',
                'Required parameter "sourceId" was null or undefined when calling listVersionsBronzeSourceIdVersionsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/bronze/{source_id}/versions`;
        urlPath = urlPath.replace(`{${"source_id"}}`, encodeURIComponent(String(requestParameters['sourceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(VersionResponseFromJSON));
    }

    /**
     * List Versions
     */
    async listVersionsBronzeSourceIdVersionsGet(requestParameters: ListVersionsBronzeSourceIdVersionsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<VersionResponse>> {
        const response = await this.listVersionsBronzeSourceIdVersionsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Source
     */
    async updateSourceBronzeSourceIdPatchRaw(requestParameters: UpdateSourceBronzeSourceIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MetadataResponse>> {
        if (requestParameters['sourceId'] == null) {
            throw new runtime.RequiredError(
                'sourceId',
                'Required parameter "sourceId" was null or undefined when calling updateSourceBronzeSourceIdPatch().'
            );
        }

        if (requestParameters['updateSourceRequest'] == null) {
            throw new runtime.RequiredError(
                'updateSourceRequest',
                'Required parameter "updateSourceRequest" was null or undefined when calling updateSourceBronzeSourceIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/bronze/{source_id}`;
        urlPath = urlPath.replace(`{${"source_id"}}`, encodeURIComponent(String(requestParameters['sourceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateSourceRequestToJSON(requestParameters['updateSourceRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MetadataResponseFromJSON(jsonValue));
    }

    /**
     * Update Source
     */
    async updateSourceBronzeSourceIdPatch(requestParameters: UpdateSourceBronzeSourceIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MetadataResponse> {
        const response = await this.updateSourceBronzeSourceIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Upload Version
     */
    async uploadVersionBronzeSourceIdVersionsPostRaw(requestParameters: UploadVersionBronzeSourceIdVersionsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['sourceId'] == null) {
            throw new runtime.RequiredError(
                'sourceId',
                'Required parameter "sourceId" was null or undefined when calling uploadVersionBronzeSourceIdVersionsPost().'
            );
        }

        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling uploadVersionBronzeSourceIdVersionsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }


        let urlPath = `/bronze/{source_id}/versions`;
        urlPath = urlPath.replace(`{${"source_id"}}`, encodeURIComponent(String(requestParameters['sourceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Upload Version
     */
    async uploadVersionBronzeSourceIdVersionsPost(requestParameters: UploadVersionBronzeSourceIdVersionsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.uploadVersionBronzeSourceIdVersionsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
