/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateGoldSourceRequest,
  GoldLineageResponse,
  GoldMetadataResponse,
  HTTPValidationError,
  UpdateGoldSourceRequest,
} from '../models/index';
import {
    CreateGoldSourceRequestFromJSON,
    CreateGoldSourceRequestToJSON,
    GoldLineageResponseFromJSON,
    GoldLineageResponseToJSON,
    GoldMetadataResponseFromJSON,
    GoldMetadataResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    UpdateGoldSourceRequestFromJSON,
    UpdateGoldSourceRequestToJSON,
} from '../models/index';

export interface CreateSourceGoldPostRequest {
    createGoldSourceRequest: CreateGoldSourceRequest;
}

export interface DeleteSourceGoldSourceIdDeleteRequest {
    sourceId: number;
}

export interface DownloadVersionGoldSourceIdVersionsVersionGetRequest {
    sourceId: number;
    version: number;
}

export interface GetSourceGoldSourceIdGetRequest {
    sourceId: number;
}

export interface ListVersionsGoldSourceIdVersionsGetRequest {
    sourceId: number;
}

export interface UpdateSourceGoldSourceIdPatchRequest {
    sourceId: number;
    updateGoldSourceRequest: UpdateGoldSourceRequest;
}

export interface UploadVersionGoldSourceIdVersionsPostRequest {
    sourceId: number;
    sources: Array<number>;
    file: string;
}

/**
 * 
 */
export class APIEndpointsForInteractingWithTheGoldLayerApi extends runtime.BaseAPI {

    /**
     * Create Source
     */
    async createSourceGoldPostRaw(requestParameters: CreateSourceGoldPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['createGoldSourceRequest'] == null) {
            throw new runtime.RequiredError(
                'createGoldSourceRequest',
                'Required parameter "createGoldSourceRequest" was null or undefined when calling createSourceGoldPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/gold/`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateGoldSourceRequestToJSON(requestParameters['createGoldSourceRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Create Source
     */
    async createSourceGoldPost(requestParameters: CreateSourceGoldPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.createSourceGoldPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Source
     */
    async deleteSourceGoldSourceIdDeleteRaw(requestParameters: DeleteSourceGoldSourceIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['sourceId'] == null) {
            throw new runtime.RequiredError(
                'sourceId',
                'Required parameter "sourceId" was null or undefined when calling deleteSourceGoldSourceIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/gold/{source_id}`;
        urlPath = urlPath.replace(`{${"source_id"}}`, encodeURIComponent(String(requestParameters['sourceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete Source
     */
    async deleteSourceGoldSourceIdDelete(requestParameters: DeleteSourceGoldSourceIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.deleteSourceGoldSourceIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Download Version
     */
    async downloadVersionGoldSourceIdVersionsVersionGetRaw(requestParameters: DownloadVersionGoldSourceIdVersionsVersionGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['sourceId'] == null) {
            throw new runtime.RequiredError(
                'sourceId',
                'Required parameter "sourceId" was null or undefined when calling downloadVersionGoldSourceIdVersionsVersionGet().'
            );
        }

        if (requestParameters['version'] == null) {
            throw new runtime.RequiredError(
                'version',
                'Required parameter "version" was null or undefined when calling downloadVersionGoldSourceIdVersionsVersionGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/gold/{source_id}/versions/{version}`;
        urlPath = urlPath.replace(`{${"source_id"}}`, encodeURIComponent(String(requestParameters['sourceId'])));
        urlPath = urlPath.replace(`{${"version"}}`, encodeURIComponent(String(requestParameters['version'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Download Version
     */
    async downloadVersionGoldSourceIdVersionsVersionGet(requestParameters: DownloadVersionGoldSourceIdVersionsVersionGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.downloadVersionGoldSourceIdVersionsVersionGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Source
     */
    async getSourceGoldSourceIdGetRaw(requestParameters: GetSourceGoldSourceIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GoldMetadataResponse>> {
        if (requestParameters['sourceId'] == null) {
            throw new runtime.RequiredError(
                'sourceId',
                'Required parameter "sourceId" was null or undefined when calling getSourceGoldSourceIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/gold/{source_id}`;
        urlPath = urlPath.replace(`{${"source_id"}}`, encodeURIComponent(String(requestParameters['sourceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GoldMetadataResponseFromJSON(jsonValue));
    }

    /**
     * Get Source
     */
    async getSourceGoldSourceIdGet(requestParameters: GetSourceGoldSourceIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GoldMetadataResponse> {
        const response = await this.getSourceGoldSourceIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Sources
     */
    async listSourcesGoldGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GoldMetadataResponse>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/gold/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GoldMetadataResponseFromJSON));
    }

    /**
     * List Sources
     */
    async listSourcesGoldGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GoldMetadataResponse>> {
        const response = await this.listSourcesGoldGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * List Versions
     */
    async listVersionsGoldSourceIdVersionsGetRaw(requestParameters: ListVersionsGoldSourceIdVersionsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GoldLineageResponse>>> {
        if (requestParameters['sourceId'] == null) {
            throw new runtime.RequiredError(
                'sourceId',
                'Required parameter "sourceId" was null or undefined when calling listVersionsGoldSourceIdVersionsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/gold/{source_id}/versions`;
        urlPath = urlPath.replace(`{${"source_id"}}`, encodeURIComponent(String(requestParameters['sourceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GoldLineageResponseFromJSON));
    }

    /**
     * List Versions
     */
    async listVersionsGoldSourceIdVersionsGet(requestParameters: ListVersionsGoldSourceIdVersionsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GoldLineageResponse>> {
        const response = await this.listVersionsGoldSourceIdVersionsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Source
     */
    async updateSourceGoldSourceIdPatchRaw(requestParameters: UpdateSourceGoldSourceIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GoldMetadataResponse>> {
        if (requestParameters['sourceId'] == null) {
            throw new runtime.RequiredError(
                'sourceId',
                'Required parameter "sourceId" was null or undefined when calling updateSourceGoldSourceIdPatch().'
            );
        }

        if (requestParameters['updateGoldSourceRequest'] == null) {
            throw new runtime.RequiredError(
                'updateGoldSourceRequest',
                'Required parameter "updateGoldSourceRequest" was null or undefined when calling updateSourceGoldSourceIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/gold/{source_id}`;
        urlPath = urlPath.replace(`{${"source_id"}}`, encodeURIComponent(String(requestParameters['sourceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateGoldSourceRequestToJSON(requestParameters['updateGoldSourceRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GoldMetadataResponseFromJSON(jsonValue));
    }

    /**
     * Update Source
     */
    async updateSourceGoldSourceIdPatch(requestParameters: UpdateSourceGoldSourceIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GoldMetadataResponse> {
        const response = await this.updateSourceGoldSourceIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Upload Version
     */
    async uploadVersionGoldSourceIdVersionsPostRaw(requestParameters: UploadVersionGoldSourceIdVersionsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['sourceId'] == null) {
            throw new runtime.RequiredError(
                'sourceId',
                'Required parameter "sourceId" was null or undefined when calling uploadVersionGoldSourceIdVersionsPost().'
            );
        }

        if (requestParameters['sources'] == null) {
            throw new runtime.RequiredError(
                'sources',
                'Required parameter "sources" was null or undefined when calling uploadVersionGoldSourceIdVersionsPost().'
            );
        }

        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling uploadVersionGoldSourceIdVersionsPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['sources'] != null) {
            queryParameters['sources'] = requestParameters['sources'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }


        let urlPath = `/gold/{source_id}/versions`;
        urlPath = urlPath.replace(`{${"source_id"}}`, encodeURIComponent(String(requestParameters['sourceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Upload Version
     */
    async uploadVersionGoldSourceIdVersionsPost(requestParameters: UploadVersionGoldSourceIdVersionsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.uploadVersionGoldSourceIdVersionsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
