/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateResourceRequest,
  CreateResourceResponse,
  HTTPValidationError,
  LineageResponse,
  MessageResponse,
  MetadataResponse,
  SchemaResponse,
  UpdateResourceRequest,
} from '../models/index';
import {
    CreateResourceRequestFromJSON,
    CreateResourceRequestToJSON,
    CreateResourceResponseFromJSON,
    CreateResourceResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    LineageResponseFromJSON,
    LineageResponseToJSON,
    MessageResponseFromJSON,
    MessageResponseToJSON,
    MetadataResponseFromJSON,
    MetadataResponseToJSON,
    SchemaResponseFromJSON,
    SchemaResponseToJSON,
    UpdateResourceRequestFromJSON,
    UpdateResourceRequestToJSON,
} from '../models/index';

export interface CreateResourceBronzePostRequest {
    createResourceRequest: CreateResourceRequest;
}

export interface DeleteResourceBronzeResourceIdDeleteRequest {
    resourceId: number;
}

export interface DownloadVersionBronzeResourceIdVersionsVersionGetRequest {
    resourceId: number;
    version: number;
}

export interface GetResourceBronzeResourceIdGetRequest {
    resourceId: number;
}

export interface GetSchemaBronzeResourceIdVersionsVersionSchemaGetRequest {
    resourceId: number;
    version: number;
}

export interface ListVersionsBronzeResourceIdVersionsGetRequest {
    resourceId: number;
}

export interface UpdateResourceBronzeResourceIdPatchRequest {
    resourceId: number;
    updateResourceRequest: UpdateResourceRequest;
}

export interface UploadVersionSingleBronzeResourceIdVersionsPostRequest {
    resourceId: number;
    fromResourceId: number;
    file: string;
}

/**
 * 
 */
export class APIEndpointsForInteractingWithTheBronzeLayerApi extends runtime.BaseAPI {

    /**
     * Create Resource
     */
    async createResourceBronzePostRaw(requestParameters: CreateResourceBronzePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateResourceResponse>> {
        if (requestParameters['createResourceRequest'] == null) {
            throw new runtime.RequiredError(
                'createResourceRequest',
                'Required parameter "createResourceRequest" was null or undefined when calling createResourceBronzePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/bronze/`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateResourceRequestToJSON(requestParameters['createResourceRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateResourceResponseFromJSON(jsonValue));
    }

    /**
     * Create Resource
     */
    async createResourceBronzePost(requestParameters: CreateResourceBronzePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateResourceResponse> {
        const response = await this.createResourceBronzePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Resource
     */
    async deleteResourceBronzeResourceIdDeleteRaw(requestParameters: DeleteResourceBronzeResourceIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MessageResponse>> {
        if (requestParameters['resourceId'] == null) {
            throw new runtime.RequiredError(
                'resourceId',
                'Required parameter "resourceId" was null or undefined when calling deleteResourceBronzeResourceIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/bronze/{resource_id}`;
        urlPath = urlPath.replace(`{${"resource_id"}}`, encodeURIComponent(String(requestParameters['resourceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageResponseFromJSON(jsonValue));
    }

    /**
     * Delete Resource
     */
    async deleteResourceBronzeResourceIdDelete(requestParameters: DeleteResourceBronzeResourceIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MessageResponse> {
        const response = await this.deleteResourceBronzeResourceIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Download Version
     */
    async downloadVersionBronzeResourceIdVersionsVersionGetRaw(requestParameters: DownloadVersionBronzeResourceIdVersionsVersionGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['resourceId'] == null) {
            throw new runtime.RequiredError(
                'resourceId',
                'Required parameter "resourceId" was null or undefined when calling downloadVersionBronzeResourceIdVersionsVersionGet().'
            );
        }

        if (requestParameters['version'] == null) {
            throw new runtime.RequiredError(
                'version',
                'Required parameter "version" was null or undefined when calling downloadVersionBronzeResourceIdVersionsVersionGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/bronze/{resource_id}/versions/{version}`;
        urlPath = urlPath.replace(`{${"resource_id"}}`, encodeURIComponent(String(requestParameters['resourceId'])));
        urlPath = urlPath.replace(`{${"version"}}`, encodeURIComponent(String(requestParameters['version'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Download Version
     */
    async downloadVersionBronzeResourceIdVersionsVersionGet(requestParameters: DownloadVersionBronzeResourceIdVersionsVersionGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.downloadVersionBronzeResourceIdVersionsVersionGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Resource
     */
    async getResourceBronzeResourceIdGetRaw(requestParameters: GetResourceBronzeResourceIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MetadataResponse>> {
        if (requestParameters['resourceId'] == null) {
            throw new runtime.RequiredError(
                'resourceId',
                'Required parameter "resourceId" was null or undefined when calling getResourceBronzeResourceIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/bronze/{resource_id}`;
        urlPath = urlPath.replace(`{${"resource_id"}}`, encodeURIComponent(String(requestParameters['resourceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MetadataResponseFromJSON(jsonValue));
    }

    /**
     * Get Resource
     */
    async getResourceBronzeResourceIdGet(requestParameters: GetResourceBronzeResourceIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MetadataResponse> {
        const response = await this.getResourceBronzeResourceIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Schema
     */
    async getSchemaBronzeResourceIdVersionsVersionSchemaGetRaw(requestParameters: GetSchemaBronzeResourceIdVersionsVersionSchemaGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SchemaResponse>> {
        if (requestParameters['resourceId'] == null) {
            throw new runtime.RequiredError(
                'resourceId',
                'Required parameter "resourceId" was null or undefined when calling getSchemaBronzeResourceIdVersionsVersionSchemaGet().'
            );
        }

        if (requestParameters['version'] == null) {
            throw new runtime.RequiredError(
                'version',
                'Required parameter "version" was null or undefined when calling getSchemaBronzeResourceIdVersionsVersionSchemaGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/bronze/{resource_id}/versions/{version}/schema`;
        urlPath = urlPath.replace(`{${"resource_id"}}`, encodeURIComponent(String(requestParameters['resourceId'])));
        urlPath = urlPath.replace(`{${"version"}}`, encodeURIComponent(String(requestParameters['version'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SchemaResponseFromJSON(jsonValue));
    }

    /**
     * Get Schema
     */
    async getSchemaBronzeResourceIdVersionsVersionSchemaGet(requestParameters: GetSchemaBronzeResourceIdVersionsVersionSchemaGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SchemaResponse> {
        const response = await this.getSchemaBronzeResourceIdVersionsVersionSchemaGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Resources
     */
    async listResourcesBronzeGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<MetadataResponse>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/bronze/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MetadataResponseFromJSON));
    }

    /**
     * List Resources
     */
    async listResourcesBronzeGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MetadataResponse>> {
        const response = await this.listResourcesBronzeGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * List Versions
     */
    async listVersionsBronzeResourceIdVersionsGetRaw(requestParameters: ListVersionsBronzeResourceIdVersionsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<LineageResponse>>> {
        if (requestParameters['resourceId'] == null) {
            throw new runtime.RequiredError(
                'resourceId',
                'Required parameter "resourceId" was null or undefined when calling listVersionsBronzeResourceIdVersionsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/bronze/{resource_id}/versions`;
        urlPath = urlPath.replace(`{${"resource_id"}}`, encodeURIComponent(String(requestParameters['resourceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(LineageResponseFromJSON));
    }

    /**
     * List Versions
     */
    async listVersionsBronzeResourceIdVersionsGet(requestParameters: ListVersionsBronzeResourceIdVersionsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<LineageResponse>> {
        const response = await this.listVersionsBronzeResourceIdVersionsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Resource
     */
    async updateResourceBronzeResourceIdPatchRaw(requestParameters: UpdateResourceBronzeResourceIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MetadataResponse>> {
        if (requestParameters['resourceId'] == null) {
            throw new runtime.RequiredError(
                'resourceId',
                'Required parameter "resourceId" was null or undefined when calling updateResourceBronzeResourceIdPatch().'
            );
        }

        if (requestParameters['updateResourceRequest'] == null) {
            throw new runtime.RequiredError(
                'updateResourceRequest',
                'Required parameter "updateResourceRequest" was null or undefined when calling updateResourceBronzeResourceIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/bronze/{resource_id}`;
        urlPath = urlPath.replace(`{${"resource_id"}}`, encodeURIComponent(String(requestParameters['resourceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateResourceRequestToJSON(requestParameters['updateResourceRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MetadataResponseFromJSON(jsonValue));
    }

    /**
     * Update Resource
     */
    async updateResourceBronzeResourceIdPatch(requestParameters: UpdateResourceBronzeResourceIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MetadataResponse> {
        const response = await this.updateResourceBronzeResourceIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Upload Version Single
     */
    async uploadVersionSingleBronzeResourceIdVersionsPostRaw(requestParameters: UploadVersionSingleBronzeResourceIdVersionsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MessageResponse>> {
        if (requestParameters['resourceId'] == null) {
            throw new runtime.RequiredError(
                'resourceId',
                'Required parameter "resourceId" was null or undefined when calling uploadVersionSingleBronzeResourceIdVersionsPost().'
            );
        }

        if (requestParameters['fromResourceId'] == null) {
            throw new runtime.RequiredError(
                'fromResourceId',
                'Required parameter "fromResourceId" was null or undefined when calling uploadVersionSingleBronzeResourceIdVersionsPost().'
            );
        }

        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling uploadVersionSingleBronzeResourceIdVersionsPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['fromResourceId'] != null) {
            queryParameters['from_resource_id'] = requestParameters['fromResourceId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }


        let urlPath = `/bronze/{resource_id}/versions`;
        urlPath = urlPath.replace(`{${"resource_id"}}`, encodeURIComponent(String(requestParameters['resourceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageResponseFromJSON(jsonValue));
    }

    /**
     * Upload Version Single
     */
    async uploadVersionSingleBronzeResourceIdVersionsPost(requestParameters: UploadVersionSingleBronzeResourceIdVersionsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MessageResponse> {
        const response = await this.uploadVersionSingleBronzeResourceIdVersionsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
