/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateGoldResourceRequest,
  CreateResourceResponse,
  GoldLineageResponse,
  GoldMetadataResponse,
  HTTPValidationError,
  MessageResponse,
  SchemaResponse,
  UpdateGoldResourceRequest,
} from '../models/index';
import {
    CreateGoldResourceRequestFromJSON,
    CreateGoldResourceRequestToJSON,
    CreateResourceResponseFromJSON,
    CreateResourceResponseToJSON,
    GoldLineageResponseFromJSON,
    GoldLineageResponseToJSON,
    GoldMetadataResponseFromJSON,
    GoldMetadataResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    MessageResponseFromJSON,
    MessageResponseToJSON,
    SchemaResponseFromJSON,
    SchemaResponseToJSON,
    UpdateGoldResourceRequestFromJSON,
    UpdateGoldResourceRequestToJSON,
} from '../models/index';

export interface CreateResourceGoldPostRequest {
    createGoldResourceRequest: CreateGoldResourceRequest;
}

export interface DeleteResourceGoldResourceIdDeleteRequest {
    resourceId: number;
}

export interface DownloadVersionGoldResourceIdVersionsVersionGetRequest {
    resourceId: number;
    version: number;
}

export interface GetResourceGoldResourceIdGetRequest {
    resourceId: number;
}

export interface GetSchemaGoldResourceIdVersionsVersionSchemaGetRequest {
    resourceId: number;
    version: number;
}

export interface ListVersionsGoldResourceIdVersionsGetRequest {
    resourceId: number;
}

export interface UpdateResourceGoldResourceIdPatchRequest {
    resourceId: number;
    updateGoldResourceRequest: UpdateGoldResourceRequest;
}

export interface UploadVersionGoldResourceIdVersionsPostRequest {
    resourceId: number;
    resources: Array<number>;
    file: string;
}

/**
 * 
 */
export class APIEndpointsForInteractingWithTheGoldLayerApi extends runtime.BaseAPI {

    /**
     * Create Resource
     */
    async createResourceGoldPostRaw(requestParameters: CreateResourceGoldPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateResourceResponse>> {
        if (requestParameters['createGoldResourceRequest'] == null) {
            throw new runtime.RequiredError(
                'createGoldResourceRequest',
                'Required parameter "createGoldResourceRequest" was null or undefined when calling createResourceGoldPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/gold/`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateGoldResourceRequestToJSON(requestParameters['createGoldResourceRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateResourceResponseFromJSON(jsonValue));
    }

    /**
     * Create Resource
     */
    async createResourceGoldPost(requestParameters: CreateResourceGoldPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateResourceResponse> {
        const response = await this.createResourceGoldPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Resource
     */
    async deleteResourceGoldResourceIdDeleteRaw(requestParameters: DeleteResourceGoldResourceIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MessageResponse>> {
        if (requestParameters['resourceId'] == null) {
            throw new runtime.RequiredError(
                'resourceId',
                'Required parameter "resourceId" was null or undefined when calling deleteResourceGoldResourceIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/gold/{resource_id}`;
        urlPath = urlPath.replace(`{${"resource_id"}}`, encodeURIComponent(String(requestParameters['resourceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageResponseFromJSON(jsonValue));
    }

    /**
     * Delete Resource
     */
    async deleteResourceGoldResourceIdDelete(requestParameters: DeleteResourceGoldResourceIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MessageResponse> {
        const response = await this.deleteResourceGoldResourceIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Download Version
     */
    async downloadVersionGoldResourceIdVersionsVersionGetRaw(requestParameters: DownloadVersionGoldResourceIdVersionsVersionGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['resourceId'] == null) {
            throw new runtime.RequiredError(
                'resourceId',
                'Required parameter "resourceId" was null or undefined when calling downloadVersionGoldResourceIdVersionsVersionGet().'
            );
        }

        if (requestParameters['version'] == null) {
            throw new runtime.RequiredError(
                'version',
                'Required parameter "version" was null or undefined when calling downloadVersionGoldResourceIdVersionsVersionGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/gold/{resource_id}/versions/{version}`;
        urlPath = urlPath.replace(`{${"resource_id"}}`, encodeURIComponent(String(requestParameters['resourceId'])));
        urlPath = urlPath.replace(`{${"version"}}`, encodeURIComponent(String(requestParameters['version'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Download Version
     */
    async downloadVersionGoldResourceIdVersionsVersionGet(requestParameters: DownloadVersionGoldResourceIdVersionsVersionGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.downloadVersionGoldResourceIdVersionsVersionGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Resource
     */
    async getResourceGoldResourceIdGetRaw(requestParameters: GetResourceGoldResourceIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GoldMetadataResponse>> {
        if (requestParameters['resourceId'] == null) {
            throw new runtime.RequiredError(
                'resourceId',
                'Required parameter "resourceId" was null or undefined when calling getResourceGoldResourceIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/gold/{resource_id}`;
        urlPath = urlPath.replace(`{${"resource_id"}}`, encodeURIComponent(String(requestParameters['resourceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GoldMetadataResponseFromJSON(jsonValue));
    }

    /**
     * Get Resource
     */
    async getResourceGoldResourceIdGet(requestParameters: GetResourceGoldResourceIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GoldMetadataResponse> {
        const response = await this.getResourceGoldResourceIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Schema
     */
    async getSchemaGoldResourceIdVersionsVersionSchemaGetRaw(requestParameters: GetSchemaGoldResourceIdVersionsVersionSchemaGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SchemaResponse>> {
        if (requestParameters['resourceId'] == null) {
            throw new runtime.RequiredError(
                'resourceId',
                'Required parameter "resourceId" was null or undefined when calling getSchemaGoldResourceIdVersionsVersionSchemaGet().'
            );
        }

        if (requestParameters['version'] == null) {
            throw new runtime.RequiredError(
                'version',
                'Required parameter "version" was null or undefined when calling getSchemaGoldResourceIdVersionsVersionSchemaGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/gold/{resource_id}/versions/{version}/schema`;
        urlPath = urlPath.replace(`{${"resource_id"}}`, encodeURIComponent(String(requestParameters['resourceId'])));
        urlPath = urlPath.replace(`{${"version"}}`, encodeURIComponent(String(requestParameters['version'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SchemaResponseFromJSON(jsonValue));
    }

    /**
     * Get Schema
     */
    async getSchemaGoldResourceIdVersionsVersionSchemaGet(requestParameters: GetSchemaGoldResourceIdVersionsVersionSchemaGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SchemaResponse> {
        const response = await this.getSchemaGoldResourceIdVersionsVersionSchemaGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Resources
     */
    async listResourcesGoldGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GoldMetadataResponse>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/gold/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GoldMetadataResponseFromJSON));
    }

    /**
     * List Resources
     */
    async listResourcesGoldGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GoldMetadataResponse>> {
        const response = await this.listResourcesGoldGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * List Versions
     */
    async listVersionsGoldResourceIdVersionsGetRaw(requestParameters: ListVersionsGoldResourceIdVersionsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GoldLineageResponse>>> {
        if (requestParameters['resourceId'] == null) {
            throw new runtime.RequiredError(
                'resourceId',
                'Required parameter "resourceId" was null or undefined when calling listVersionsGoldResourceIdVersionsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/gold/{resource_id}/versions`;
        urlPath = urlPath.replace(`{${"resource_id"}}`, encodeURIComponent(String(requestParameters['resourceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GoldLineageResponseFromJSON));
    }

    /**
     * List Versions
     */
    async listVersionsGoldResourceIdVersionsGet(requestParameters: ListVersionsGoldResourceIdVersionsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GoldLineageResponse>> {
        const response = await this.listVersionsGoldResourceIdVersionsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Resource
     */
    async updateResourceGoldResourceIdPatchRaw(requestParameters: UpdateResourceGoldResourceIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GoldMetadataResponse>> {
        if (requestParameters['resourceId'] == null) {
            throw new runtime.RequiredError(
                'resourceId',
                'Required parameter "resourceId" was null or undefined when calling updateResourceGoldResourceIdPatch().'
            );
        }

        if (requestParameters['updateGoldResourceRequest'] == null) {
            throw new runtime.RequiredError(
                'updateGoldResourceRequest',
                'Required parameter "updateGoldResourceRequest" was null or undefined when calling updateResourceGoldResourceIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/gold/{resource_id}`;
        urlPath = urlPath.replace(`{${"resource_id"}}`, encodeURIComponent(String(requestParameters['resourceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateGoldResourceRequestToJSON(requestParameters['updateGoldResourceRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GoldMetadataResponseFromJSON(jsonValue));
    }

    /**
     * Update Resource
     */
    async updateResourceGoldResourceIdPatch(requestParameters: UpdateResourceGoldResourceIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GoldMetadataResponse> {
        const response = await this.updateResourceGoldResourceIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Upload Version
     */
    async uploadVersionGoldResourceIdVersionsPostRaw(requestParameters: UploadVersionGoldResourceIdVersionsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MessageResponse>> {
        if (requestParameters['resourceId'] == null) {
            throw new runtime.RequiredError(
                'resourceId',
                'Required parameter "resourceId" was null or undefined when calling uploadVersionGoldResourceIdVersionsPost().'
            );
        }

        if (requestParameters['resources'] == null) {
            throw new runtime.RequiredError(
                'resources',
                'Required parameter "resources" was null or undefined when calling uploadVersionGoldResourceIdVersionsPost().'
            );
        }

        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling uploadVersionGoldResourceIdVersionsPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['resources'] != null) {
            queryParameters['resources'] = requestParameters['resources'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }


        let urlPath = `/gold/{resource_id}/versions`;
        urlPath = urlPath.replace(`{${"resource_id"}}`, encodeURIComponent(String(requestParameters['resourceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageResponseFromJSON(jsonValue));
    }

    /**
     * Upload Version
     */
    async uploadVersionGoldResourceIdVersionsPost(requestParameters: UploadVersionGoldResourceIdVersionsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MessageResponse> {
        const response = await this.uploadVersionGoldResourceIdVersionsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
