/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateResourceRequest,
  CreateResourceResponse,
  HTTPValidationError,
  LineageResponse,
  MessageResponse,
  MetadataResponse,
  SchemaResponse,
  UpdateResourceRequest,
} from '../models/index';
import {
    CreateResourceRequestFromJSON,
    CreateResourceRequestToJSON,
    CreateResourceResponseFromJSON,
    CreateResourceResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    LineageResponseFromJSON,
    LineageResponseToJSON,
    MessageResponseFromJSON,
    MessageResponseToJSON,
    MetadataResponseFromJSON,
    MetadataResponseToJSON,
    SchemaResponseFromJSON,
    SchemaResponseToJSON,
    UpdateResourceRequestFromJSON,
    UpdateResourceRequestToJSON,
} from '../models/index';

export interface CreateResourceSilverPostRequest {
    createResourceRequest: CreateResourceRequest;
}

export interface DeleteResourceSilverResourceIdDeleteRequest {
    resourceId: number;
}

export interface DownloadVersionSilverResourceIdVersionsVersionGetRequest {
    resourceId: number;
    version: number;
}

export interface GetResourceSilverResourceIdGetRequest {
    resourceId: number;
}

export interface GetSchemaSilverResourceIdVersionsVersionSchemaGetRequest {
    resourceId: number;
    version: number;
}

export interface ListVersionsSilverResourceIdVersionsGetRequest {
    resourceId: number;
}

export interface UpdateResourceSilverResourceIdPatchRequest {
    resourceId: number;
    updateResourceRequest: UpdateResourceRequest;
}

export interface UploadVersionSingleSilverResourceIdVersionsPostRequest {
    resourceId: number;
    fromResourceId: number;
    file: string;
}

/**
 * 
 */
export class APIEndpointsForInteractingWithTheSilverLayerApi extends runtime.BaseAPI {

    /**
     * Create Resource
     */
    async createResourceSilverPostRaw(requestParameters: CreateResourceSilverPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateResourceResponse>> {
        if (requestParameters['createResourceRequest'] == null) {
            throw new runtime.RequiredError(
                'createResourceRequest',
                'Required parameter "createResourceRequest" was null or undefined when calling createResourceSilverPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/silver/`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateResourceRequestToJSON(requestParameters['createResourceRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateResourceResponseFromJSON(jsonValue));
    }

    /**
     * Create Resource
     */
    async createResourceSilverPost(requestParameters: CreateResourceSilverPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateResourceResponse> {
        const response = await this.createResourceSilverPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Resource
     */
    async deleteResourceSilverResourceIdDeleteRaw(requestParameters: DeleteResourceSilverResourceIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MessageResponse>> {
        if (requestParameters['resourceId'] == null) {
            throw new runtime.RequiredError(
                'resourceId',
                'Required parameter "resourceId" was null or undefined when calling deleteResourceSilverResourceIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/silver/{resource_id}`;
        urlPath = urlPath.replace(`{${"resource_id"}}`, encodeURIComponent(String(requestParameters['resourceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageResponseFromJSON(jsonValue));
    }

    /**
     * Delete Resource
     */
    async deleteResourceSilverResourceIdDelete(requestParameters: DeleteResourceSilverResourceIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MessageResponse> {
        const response = await this.deleteResourceSilverResourceIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Download Version
     */
    async downloadVersionSilverResourceIdVersionsVersionGetRaw(requestParameters: DownloadVersionSilverResourceIdVersionsVersionGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['resourceId'] == null) {
            throw new runtime.RequiredError(
                'resourceId',
                'Required parameter "resourceId" was null or undefined when calling downloadVersionSilverResourceIdVersionsVersionGet().'
            );
        }

        if (requestParameters['version'] == null) {
            throw new runtime.RequiredError(
                'version',
                'Required parameter "version" was null or undefined when calling downloadVersionSilverResourceIdVersionsVersionGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/silver/{resource_id}/versions/{version}`;
        urlPath = urlPath.replace(`{${"resource_id"}}`, encodeURIComponent(String(requestParameters['resourceId'])));
        urlPath = urlPath.replace(`{${"version"}}`, encodeURIComponent(String(requestParameters['version'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Download Version
     */
    async downloadVersionSilverResourceIdVersionsVersionGet(requestParameters: DownloadVersionSilverResourceIdVersionsVersionGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.downloadVersionSilverResourceIdVersionsVersionGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Resource
     */
    async getResourceSilverResourceIdGetRaw(requestParameters: GetResourceSilverResourceIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MetadataResponse>> {
        if (requestParameters['resourceId'] == null) {
            throw new runtime.RequiredError(
                'resourceId',
                'Required parameter "resourceId" was null or undefined when calling getResourceSilverResourceIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/silver/{resource_id}`;
        urlPath = urlPath.replace(`{${"resource_id"}}`, encodeURIComponent(String(requestParameters['resourceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MetadataResponseFromJSON(jsonValue));
    }

    /**
     * Get Resource
     */
    async getResourceSilverResourceIdGet(requestParameters: GetResourceSilverResourceIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MetadataResponse> {
        const response = await this.getResourceSilverResourceIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Schema
     */
    async getSchemaSilverResourceIdVersionsVersionSchemaGetRaw(requestParameters: GetSchemaSilverResourceIdVersionsVersionSchemaGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SchemaResponse>> {
        if (requestParameters['resourceId'] == null) {
            throw new runtime.RequiredError(
                'resourceId',
                'Required parameter "resourceId" was null or undefined when calling getSchemaSilverResourceIdVersionsVersionSchemaGet().'
            );
        }

        if (requestParameters['version'] == null) {
            throw new runtime.RequiredError(
                'version',
                'Required parameter "version" was null or undefined when calling getSchemaSilverResourceIdVersionsVersionSchemaGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/silver/{resource_id}/versions/{version}/schema`;
        urlPath = urlPath.replace(`{${"resource_id"}}`, encodeURIComponent(String(requestParameters['resourceId'])));
        urlPath = urlPath.replace(`{${"version"}}`, encodeURIComponent(String(requestParameters['version'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SchemaResponseFromJSON(jsonValue));
    }

    /**
     * Get Schema
     */
    async getSchemaSilverResourceIdVersionsVersionSchemaGet(requestParameters: GetSchemaSilverResourceIdVersionsVersionSchemaGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SchemaResponse> {
        const response = await this.getSchemaSilverResourceIdVersionsVersionSchemaGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Resources
     */
    async listResourcesSilverGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<MetadataResponse>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/silver/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MetadataResponseFromJSON));
    }

    /**
     * List Resources
     */
    async listResourcesSilverGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MetadataResponse>> {
        const response = await this.listResourcesSilverGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * List Versions
     */
    async listVersionsSilverResourceIdVersionsGetRaw(requestParameters: ListVersionsSilverResourceIdVersionsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<LineageResponse>>> {
        if (requestParameters['resourceId'] == null) {
            throw new runtime.RequiredError(
                'resourceId',
                'Required parameter "resourceId" was null or undefined when calling listVersionsSilverResourceIdVersionsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/silver/{resource_id}/versions`;
        urlPath = urlPath.replace(`{${"resource_id"}}`, encodeURIComponent(String(requestParameters['resourceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(LineageResponseFromJSON));
    }

    /**
     * List Versions
     */
    async listVersionsSilverResourceIdVersionsGet(requestParameters: ListVersionsSilverResourceIdVersionsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<LineageResponse>> {
        const response = await this.listVersionsSilverResourceIdVersionsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Resource
     */
    async updateResourceSilverResourceIdPatchRaw(requestParameters: UpdateResourceSilverResourceIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MetadataResponse>> {
        if (requestParameters['resourceId'] == null) {
            throw new runtime.RequiredError(
                'resourceId',
                'Required parameter "resourceId" was null or undefined when calling updateResourceSilverResourceIdPatch().'
            );
        }

        if (requestParameters['updateResourceRequest'] == null) {
            throw new runtime.RequiredError(
                'updateResourceRequest',
                'Required parameter "updateResourceRequest" was null or undefined when calling updateResourceSilverResourceIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/silver/{resource_id}`;
        urlPath = urlPath.replace(`{${"resource_id"}}`, encodeURIComponent(String(requestParameters['resourceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateResourceRequestToJSON(requestParameters['updateResourceRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MetadataResponseFromJSON(jsonValue));
    }

    /**
     * Update Resource
     */
    async updateResourceSilverResourceIdPatch(requestParameters: UpdateResourceSilverResourceIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MetadataResponse> {
        const response = await this.updateResourceSilverResourceIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Upload Version Single
     */
    async uploadVersionSingleSilverResourceIdVersionsPostRaw(requestParameters: UploadVersionSingleSilverResourceIdVersionsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MessageResponse>> {
        if (requestParameters['resourceId'] == null) {
            throw new runtime.RequiredError(
                'resourceId',
                'Required parameter "resourceId" was null or undefined when calling uploadVersionSingleSilverResourceIdVersionsPost().'
            );
        }

        if (requestParameters['fromResourceId'] == null) {
            throw new runtime.RequiredError(
                'fromResourceId',
                'Required parameter "fromResourceId" was null or undefined when calling uploadVersionSingleSilverResourceIdVersionsPost().'
            );
        }

        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling uploadVersionSingleSilverResourceIdVersionsPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['fromResourceId'] != null) {
            queryParameters['from_resource_id'] = requestParameters['fromResourceId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }


        let urlPath = `/silver/{resource_id}/versions`;
        urlPath = urlPath.replace(`{${"resource_id"}}`, encodeURIComponent(String(requestParameters['resourceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageResponseFromJSON(jsonValue));
    }

    /**
     * Upload Version Single
     */
    async uploadVersionSingleSilverResourceIdVersionsPost(requestParameters: UploadVersionSingleSilverResourceIdVersionsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MessageResponse> {
        const response = await this.uploadVersionSingleSilverResourceIdVersionsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
