/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateSilverSourceRequest,
  HTTPValidationError,
  SilverLineageResponse,
  SilverMetadataResponse,
  UpdateSilverSourceRequest,
} from '../models/index';
import {
    CreateSilverSourceRequestFromJSON,
    CreateSilverSourceRequestToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    SilverLineageResponseFromJSON,
    SilverLineageResponseToJSON,
    SilverMetadataResponseFromJSON,
    SilverMetadataResponseToJSON,
    UpdateSilverSourceRequestFromJSON,
    UpdateSilverSourceRequestToJSON,
} from '../models/index';

export interface CreateSourceSilverPostRequest {
    createSilverSourceRequest: CreateSilverSourceRequest;
}

export interface DeleteSourceSilverSourceIdDeleteRequest {
    sourceId: number;
}

export interface DownloadVersionSilverSourceIdVersionsVersionGetRequest {
    sourceId: number;
    version: number;
}

export interface GetSourceSilverSourceIdGetRequest {
    sourceId: number;
}

export interface ListVersionsSilverSourceIdVersionsGetRequest {
    sourceId: number;
}

export interface UpdateSourceSilverSourceIdPatchRequest {
    sourceId: number;
    updateSilverSourceRequest: UpdateSilverSourceRequest;
}

export interface UploadVersionSilverSourceIdVersionsPostRequest {
    sourceId: number;
    fromSourceId: number;
    file: string;
}

/**
 * 
 */
export class APIEndpointsForInteractingWithTheSilverLayerApi extends runtime.BaseAPI {

    /**
     * Create Source
     */
    async createSourceSilverPostRaw(requestParameters: CreateSourceSilverPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['createSilverSourceRequest'] == null) {
            throw new runtime.RequiredError(
                'createSilverSourceRequest',
                'Required parameter "createSilverSourceRequest" was null or undefined when calling createSourceSilverPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/silver/`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateSilverSourceRequestToJSON(requestParameters['createSilverSourceRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Create Source
     */
    async createSourceSilverPost(requestParameters: CreateSourceSilverPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.createSourceSilverPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Source
     */
    async deleteSourceSilverSourceIdDeleteRaw(requestParameters: DeleteSourceSilverSourceIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['sourceId'] == null) {
            throw new runtime.RequiredError(
                'sourceId',
                'Required parameter "sourceId" was null or undefined when calling deleteSourceSilverSourceIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/silver/{source_id}`;
        urlPath = urlPath.replace(`{${"source_id"}}`, encodeURIComponent(String(requestParameters['sourceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete Source
     */
    async deleteSourceSilverSourceIdDelete(requestParameters: DeleteSourceSilverSourceIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.deleteSourceSilverSourceIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Download Version
     */
    async downloadVersionSilverSourceIdVersionsVersionGetRaw(requestParameters: DownloadVersionSilverSourceIdVersionsVersionGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['sourceId'] == null) {
            throw new runtime.RequiredError(
                'sourceId',
                'Required parameter "sourceId" was null or undefined when calling downloadVersionSilverSourceIdVersionsVersionGet().'
            );
        }

        if (requestParameters['version'] == null) {
            throw new runtime.RequiredError(
                'version',
                'Required parameter "version" was null or undefined when calling downloadVersionSilverSourceIdVersionsVersionGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/silver/{source_id}/versions/{version}`;
        urlPath = urlPath.replace(`{${"source_id"}}`, encodeURIComponent(String(requestParameters['sourceId'])));
        urlPath = urlPath.replace(`{${"version"}}`, encodeURIComponent(String(requestParameters['version'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Download Version
     */
    async downloadVersionSilverSourceIdVersionsVersionGet(requestParameters: DownloadVersionSilverSourceIdVersionsVersionGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.downloadVersionSilverSourceIdVersionsVersionGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Source
     */
    async getSourceSilverSourceIdGetRaw(requestParameters: GetSourceSilverSourceIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SilverMetadataResponse>> {
        if (requestParameters['sourceId'] == null) {
            throw new runtime.RequiredError(
                'sourceId',
                'Required parameter "sourceId" was null or undefined when calling getSourceSilverSourceIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/silver/{source_id}`;
        urlPath = urlPath.replace(`{${"source_id"}}`, encodeURIComponent(String(requestParameters['sourceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SilverMetadataResponseFromJSON(jsonValue));
    }

    /**
     * Get Source
     */
    async getSourceSilverSourceIdGet(requestParameters: GetSourceSilverSourceIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SilverMetadataResponse> {
        const response = await this.getSourceSilverSourceIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Sources
     */
    async listSourcesSilverGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SilverMetadataResponse>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/silver/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SilverMetadataResponseFromJSON));
    }

    /**
     * List Sources
     */
    async listSourcesSilverGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SilverMetadataResponse>> {
        const response = await this.listSourcesSilverGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * List Versions
     */
    async listVersionsSilverSourceIdVersionsGetRaw(requestParameters: ListVersionsSilverSourceIdVersionsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SilverLineageResponse>>> {
        if (requestParameters['sourceId'] == null) {
            throw new runtime.RequiredError(
                'sourceId',
                'Required parameter "sourceId" was null or undefined when calling listVersionsSilverSourceIdVersionsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/silver/{source_id}/versions`;
        urlPath = urlPath.replace(`{${"source_id"}}`, encodeURIComponent(String(requestParameters['sourceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SilverLineageResponseFromJSON));
    }

    /**
     * List Versions
     */
    async listVersionsSilverSourceIdVersionsGet(requestParameters: ListVersionsSilverSourceIdVersionsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SilverLineageResponse>> {
        const response = await this.listVersionsSilverSourceIdVersionsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Source
     */
    async updateSourceSilverSourceIdPatchRaw(requestParameters: UpdateSourceSilverSourceIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SilverMetadataResponse>> {
        if (requestParameters['sourceId'] == null) {
            throw new runtime.RequiredError(
                'sourceId',
                'Required parameter "sourceId" was null or undefined when calling updateSourceSilverSourceIdPatch().'
            );
        }

        if (requestParameters['updateSilverSourceRequest'] == null) {
            throw new runtime.RequiredError(
                'updateSilverSourceRequest',
                'Required parameter "updateSilverSourceRequest" was null or undefined when calling updateSourceSilverSourceIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/silver/{source_id}`;
        urlPath = urlPath.replace(`{${"source_id"}}`, encodeURIComponent(String(requestParameters['sourceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateSilverSourceRequestToJSON(requestParameters['updateSilverSourceRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SilverMetadataResponseFromJSON(jsonValue));
    }

    /**
     * Update Source
     */
    async updateSourceSilverSourceIdPatch(requestParameters: UpdateSourceSilverSourceIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SilverMetadataResponse> {
        const response = await this.updateSourceSilverSourceIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Upload Version
     */
    async uploadVersionSilverSourceIdVersionsPostRaw(requestParameters: UploadVersionSilverSourceIdVersionsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['sourceId'] == null) {
            throw new runtime.RequiredError(
                'sourceId',
                'Required parameter "sourceId" was null or undefined when calling uploadVersionSilverSourceIdVersionsPost().'
            );
        }

        if (requestParameters['fromSourceId'] == null) {
            throw new runtime.RequiredError(
                'fromSourceId',
                'Required parameter "fromSourceId" was null or undefined when calling uploadVersionSilverSourceIdVersionsPost().'
            );
        }

        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling uploadVersionSilverSourceIdVersionsPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['fromSourceId'] != null) {
            queryParameters['from_source_id'] = requestParameters['fromSourceId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }


        let urlPath = `/silver/{source_id}/versions`;
        urlPath = urlPath.replace(`{${"source_id"}}`, encodeURIComponent(String(requestParameters['sourceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Upload Version
     */
    async uploadVersionSilverSourceIdVersionsPost(requestParameters: UploadVersionSilverSourceIdVersionsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.uploadVersionSilverSourceIdVersionsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
