/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateResourceRequest,
  CreateResourceResponse,
  HTTPValidationError,
  MessageResponse,
  MetadataResponse,
  UpdateResourceRequest,
  VersionResponse,
} from '../models/index';
import {
    CreateResourceRequestFromJSON,
    CreateResourceRequestToJSON,
    CreateResourceResponseFromJSON,
    CreateResourceResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    MessageResponseFromJSON,
    MessageResponseToJSON,
    MetadataResponseFromJSON,
    MetadataResponseToJSON,
    UpdateResourceRequestFromJSON,
    UpdateResourceRequestToJSON,
    VersionResponseFromJSON,
    VersionResponseToJSON,
} from '../models/index';

export interface ActivateVersionRawResourceIdVersionsVersionPatchRequest {
    resourceId: number;
    version: number;
}

export interface CreateResourceRawPostRequest {
    createResourceRequest: CreateResourceRequest;
}

export interface DeleteResourceRawResourceIdDeleteRequest {
    resourceId: number;
}

export interface DeleteVersionRawResourceIdVersionsVersionDeleteRequest {
    resourceId: number;
    version: number;
}

export interface DownloadVersionRawResourceIdVersionsVersionGetRequest {
    resourceId: number;
    version: number;
}

export interface GetResourceRawResourceIdGetRequest {
    resourceId: number;
}

export interface ListVersionsRawResourceIdVersionsGetRequest {
    resourceId: number;
}

export interface UpdateResourceRawResourceIdPatchRequest {
    resourceId: number;
    updateResourceRequest: UpdateResourceRequest;
}

export interface UploadVersionRawResourceIdVersionsPostRequest {
    resourceId: number;
    file: string;
}

/**
 * 
 */
export class RawApi extends runtime.BaseAPI {

    /**
     * Set a specific version of a Raw layer resource as the active version.  Args:         resource_id (int): The id of the Raw resource.         version (int): The version number to activate.  Returns:         MessageResponse: Confirmation message. 404 if the version does not exist.
     * Activate Version
     */
    async activateVersionRawResourceIdVersionsVersionPatchRaw(requestParameters: ActivateVersionRawResourceIdVersionsVersionPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MessageResponse>> {
        if (requestParameters['resourceId'] == null) {
            throw new runtime.RequiredError(
                'resourceId',
                'Required parameter "resourceId" was null or undefined when calling activateVersionRawResourceIdVersionsVersionPatch().'
            );
        }

        if (requestParameters['version'] == null) {
            throw new runtime.RequiredError(
                'version',
                'Required parameter "version" was null or undefined when calling activateVersionRawResourceIdVersionsVersionPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/raw/{resource_id}/versions/{version}`;
        urlPath = urlPath.replace(`{${"resource_id"}}`, encodeURIComponent(String(requestParameters['resourceId'])));
        urlPath = urlPath.replace(`{${"version"}}`, encodeURIComponent(String(requestParameters['version'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageResponseFromJSON(jsonValue));
    }

    /**
     * Set a specific version of a Raw layer resource as the active version.  Args:         resource_id (int): The id of the Raw resource.         version (int): The version number to activate.  Returns:         MessageResponse: Confirmation message. 404 if the version does not exist.
     * Activate Version
     */
    async activateVersionRawResourceIdVersionsVersionPatch(requestParameters: ActivateVersionRawResourceIdVersionsVersionPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MessageResponse> {
        const response = await this.activateVersionRawResourceIdVersionsVersionPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new Raw layer resource.  Args:         body (CreateResourceRequest): name (str), project_id (int),                 description (str | None).  Returns:         CreateResourceResponse: Confirmation message and the new resource_id (int).
     * Create Resource
     */
    async createResourceRawPostRaw(requestParameters: CreateResourceRawPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateResourceResponse>> {
        if (requestParameters['createResourceRequest'] == null) {
            throw new runtime.RequiredError(
                'createResourceRequest',
                'Required parameter "createResourceRequest" was null or undefined when calling createResourceRawPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/raw/`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateResourceRequestToJSON(requestParameters['createResourceRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateResourceResponseFromJSON(jsonValue));
    }

    /**
     * Create a new Raw layer resource.  Args:         body (CreateResourceRequest): name (str), project_id (int),                 description (str | None).  Returns:         CreateResourceResponse: Confirmation message and the new resource_id (int).
     * Create Resource
     */
    async createResourceRawPost(requestParameters: CreateResourceRawPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateResourceResponse> {
        const response = await this.createResourceRawPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a Raw layer resource and all its associated versions.  Args:         resource_id (int): The id of the Raw resource to delete.  Returns:         MessageResponse: Confirmation message.
     * Delete Resource
     */
    async deleteResourceRawResourceIdDeleteRaw(requestParameters: DeleteResourceRawResourceIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MessageResponse>> {
        if (requestParameters['resourceId'] == null) {
            throw new runtime.RequiredError(
                'resourceId',
                'Required parameter "resourceId" was null or undefined when calling deleteResourceRawResourceIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/raw/{resource_id}`;
        urlPath = urlPath.replace(`{${"resource_id"}}`, encodeURIComponent(String(requestParameters['resourceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageResponseFromJSON(jsonValue));
    }

    /**
     * Delete a Raw layer resource and all its associated versions.  Args:         resource_id (int): The id of the Raw resource to delete.  Returns:         MessageResponse: Confirmation message.
     * Delete Resource
     */
    async deleteResourceRawResourceIdDelete(requestParameters: DeleteResourceRawResourceIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MessageResponse> {
        const response = await this.deleteResourceRawResourceIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a specific version of a Raw layer resource, removing it from S3 and the database.  Args:         resource_id (int): The id of the Raw resource.         version (int): The version number to delete.  Returns:         MessageResponse: Confirmation message. 404 if the version does not exist.
     * Delete Version
     */
    async deleteVersionRawResourceIdVersionsVersionDeleteRaw(requestParameters: DeleteVersionRawResourceIdVersionsVersionDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MessageResponse>> {
        if (requestParameters['resourceId'] == null) {
            throw new runtime.RequiredError(
                'resourceId',
                'Required parameter "resourceId" was null or undefined when calling deleteVersionRawResourceIdVersionsVersionDelete().'
            );
        }

        if (requestParameters['version'] == null) {
            throw new runtime.RequiredError(
                'version',
                'Required parameter "version" was null or undefined when calling deleteVersionRawResourceIdVersionsVersionDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/raw/{resource_id}/versions/{version}`;
        urlPath = urlPath.replace(`{${"resource_id"}}`, encodeURIComponent(String(requestParameters['resourceId'])));
        urlPath = urlPath.replace(`{${"version"}}`, encodeURIComponent(String(requestParameters['version'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageResponseFromJSON(jsonValue));
    }

    /**
     * Delete a specific version of a Raw layer resource, removing it from S3 and the database.  Args:         resource_id (int): The id of the Raw resource.         version (int): The version number to delete.  Returns:         MessageResponse: Confirmation message. 404 if the version does not exist.
     * Delete Version
     */
    async deleteVersionRawResourceIdVersionsVersionDelete(requestParameters: DeleteVersionRawResourceIdVersionsVersionDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MessageResponse> {
        const response = await this.deleteVersionRawResourceIdVersionsVersionDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Download the raw file for a specific version of a Raw layer resource.  Args:         resource_id (int): The id of the Raw resource.         version (int): The version number to download.  Returns:         StreamingResponse: The raw file as an octet-stream attachment. 404 if the file                 is not found.
     * Download Version
     */
    async downloadVersionRawResourceIdVersionsVersionGetRaw(requestParameters: DownloadVersionRawResourceIdVersionsVersionGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['resourceId'] == null) {
            throw new runtime.RequiredError(
                'resourceId',
                'Required parameter "resourceId" was null or undefined when calling downloadVersionRawResourceIdVersionsVersionGet().'
            );
        }

        if (requestParameters['version'] == null) {
            throw new runtime.RequiredError(
                'version',
                'Required parameter "version" was null or undefined when calling downloadVersionRawResourceIdVersionsVersionGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/raw/{resource_id}/versions/{version}`;
        urlPath = urlPath.replace(`{${"resource_id"}}`, encodeURIComponent(String(requestParameters['resourceId'])));
        urlPath = urlPath.replace(`{${"version"}}`, encodeURIComponent(String(requestParameters['version'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Download the raw file for a specific version of a Raw layer resource.  Args:         resource_id (int): The id of the Raw resource.         version (int): The version number to download.  Returns:         StreamingResponse: The raw file as an octet-stream attachment. 404 if the file                 is not found.
     * Download Version
     */
    async downloadVersionRawResourceIdVersionsVersionGet(requestParameters: DownloadVersionRawResourceIdVersionsVersionGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.downloadVersionRawResourceIdVersionsVersionGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Return metadata for a single Raw layer resource.  Args:         resource_id (int): The id of the Raw resource.  Returns:         MetadataResponse: Resource id, name, description, project_id, and created_at.                 404 if not found.
     * Get Resource
     */
    async getResourceRawResourceIdGetRaw(requestParameters: GetResourceRawResourceIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MetadataResponse>> {
        if (requestParameters['resourceId'] == null) {
            throw new runtime.RequiredError(
                'resourceId',
                'Required parameter "resourceId" was null or undefined when calling getResourceRawResourceIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/raw/{resource_id}`;
        urlPath = urlPath.replace(`{${"resource_id"}}`, encodeURIComponent(String(requestParameters['resourceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MetadataResponseFromJSON(jsonValue));
    }

    /**
     * Return metadata for a single Raw layer resource.  Args:         resource_id (int): The id of the Raw resource.  Returns:         MetadataResponse: Resource id, name, description, project_id, and created_at.                 404 if not found.
     * Get Resource
     */
    async getResourceRawResourceIdGet(requestParameters: GetResourceRawResourceIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MetadataResponse> {
        const response = await this.getResourceRawResourceIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Return metadata for all Raw layer resources across all projects.  Returns:         list[MetadataResponse]: All Raw resources with id, name, description,                 project_id, and created_at.
     * List Resources
     */
    async listResourcesRawGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<MetadataResponse>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/raw/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MetadataResponseFromJSON));
    }

    /**
     * Return metadata for all Raw layer resources across all projects.  Returns:         list[MetadataResponse]: All Raw resources with id, name, description,                 project_id, and created_at.
     * List Resources
     */
    async listResourcesRawGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MetadataResponse>> {
        const response = await this.listResourcesRawGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * List all uploaded file versions for a Raw layer resource.  Args:         resource_id (int): The id of the Raw resource.  Returns:         list[VersionResponse]: Each entry contains id, resource_id, version (int),                 status (\'active\'/\'inactive\'), s3_key, created_at, and updated_at.
     * List Versions
     */
    async listVersionsRawResourceIdVersionsGetRaw(requestParameters: ListVersionsRawResourceIdVersionsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<VersionResponse>>> {
        if (requestParameters['resourceId'] == null) {
            throw new runtime.RequiredError(
                'resourceId',
                'Required parameter "resourceId" was null or undefined when calling listVersionsRawResourceIdVersionsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/raw/{resource_id}/versions`;
        urlPath = urlPath.replace(`{${"resource_id"}}`, encodeURIComponent(String(requestParameters['resourceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(VersionResponseFromJSON));
    }

    /**
     * List all uploaded file versions for a Raw layer resource.  Args:         resource_id (int): The id of the Raw resource.  Returns:         list[VersionResponse]: Each entry contains id, resource_id, version (int),                 status (\'active\'/\'inactive\'), s3_key, created_at, and updated_at.
     * List Versions
     */
    async listVersionsRawResourceIdVersionsGet(requestParameters: ListVersionsRawResourceIdVersionsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<VersionResponse>> {
        const response = await this.listVersionsRawResourceIdVersionsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update the name and/or description of a Raw layer resource.  Args:         resource_id (int): The id of the Raw resource to update.         body (UpdateResourceRequest): name (str), description (str | None).  Returns:         MetadataResponse: Updated resource metadata. 404 if not found.
     * Update Resource
     */
    async updateResourceRawResourceIdPatchRaw(requestParameters: UpdateResourceRawResourceIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MetadataResponse>> {
        if (requestParameters['resourceId'] == null) {
            throw new runtime.RequiredError(
                'resourceId',
                'Required parameter "resourceId" was null or undefined when calling updateResourceRawResourceIdPatch().'
            );
        }

        if (requestParameters['updateResourceRequest'] == null) {
            throw new runtime.RequiredError(
                'updateResourceRequest',
                'Required parameter "updateResourceRequest" was null or undefined when calling updateResourceRawResourceIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/raw/{resource_id}`;
        urlPath = urlPath.replace(`{${"resource_id"}}`, encodeURIComponent(String(requestParameters['resourceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateResourceRequestToJSON(requestParameters['updateResourceRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MetadataResponseFromJSON(jsonValue));
    }

    /**
     * Update the name and/or description of a Raw layer resource.  Args:         resource_id (int): The id of the Raw resource to update.         body (UpdateResourceRequest): name (str), description (str | None).  Returns:         MetadataResponse: Updated resource metadata. 404 if not found.
     * Update Resource
     */
    async updateResourceRawResourceIdPatch(requestParameters: UpdateResourceRawResourceIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MetadataResponse> {
        const response = await this.updateResourceRawResourceIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Upload a new raw file as a new version of a Raw layer resource. Stored in S3; a version record is created in the database.  Args:         resource_id (int): The id of the Raw resource to upload to.         file (UploadFile): The raw file to upload.  Returns:         MessageResponse: Confirmation message.
     * Upload Version
     */
    async uploadVersionRawResourceIdVersionsPostRaw(requestParameters: UploadVersionRawResourceIdVersionsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MessageResponse>> {
        if (requestParameters['resourceId'] == null) {
            throw new runtime.RequiredError(
                'resourceId',
                'Required parameter "resourceId" was null or undefined when calling uploadVersionRawResourceIdVersionsPost().'
            );
        }

        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling uploadVersionRawResourceIdVersionsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }


        let urlPath = `/raw/{resource_id}/versions`;
        urlPath = urlPath.replace(`{${"resource_id"}}`, encodeURIComponent(String(requestParameters['resourceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageResponseFromJSON(jsonValue));
    }

    /**
     * Upload a new raw file as a new version of a Raw layer resource. Stored in S3; a version record is created in the database.  Args:         resource_id (int): The id of the Raw resource to upload to.         file (UploadFile): The raw file to upload.  Returns:         MessageResponse: Confirmation message.
     * Upload Version
     */
    async uploadVersionRawResourceIdVersionsPost(requestParameters: UploadVersionRawResourceIdVersionsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MessageResponse> {
        const response = await this.uploadVersionRawResourceIdVersionsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
