/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateResourceRequest,
  CreateResourceResponse,
  HTTPValidationError,
  LineageResponse,
  MessageResponse,
  MetadataResponse,
  SchemaResponse,
  UpdateResourceRequest,
} from '../models/index';
import {
    CreateResourceRequestFromJSON,
    CreateResourceRequestToJSON,
    CreateResourceResponseFromJSON,
    CreateResourceResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    LineageResponseFromJSON,
    LineageResponseToJSON,
    MessageResponseFromJSON,
    MessageResponseToJSON,
    MetadataResponseFromJSON,
    MetadataResponseToJSON,
    SchemaResponseFromJSON,
    SchemaResponseToJSON,
    UpdateResourceRequestFromJSON,
    UpdateResourceRequestToJSON,
} from '../models/index';

export interface SilverCreateResourceRequest {
    createResourceRequest: CreateResourceRequest;
}

export interface SilverDeleteResourceRequest {
    resourceId: number;
}

export interface SilverDownloadVersionRequest {
    resourceId: number;
    version: number;
}

export interface SilverGetResourceRequest {
    resourceId: number;
}

export interface SilverGetSchemaRequest {
    resourceId: number;
    version: number;
}

export interface SilverListVersionsRequest {
    resourceId: number;
}

export interface SilverUpdateResourceRequest {
    resourceId: number;
    updateResourceRequest: UpdateResourceRequest;
}

export interface SilverUploadVersionRequest {
    resourceId: number;
    fromResourceId: number;
    file: string;
}

/**
 * 
 */
export class SilverApi extends runtime.BaseAPI {

    /**
     * Creates a new resource in the layer.  Args:         body: A CreateResourceRequest object containing the name, project ID, and                 optional description for the new resource.         loader: The loader instance to use for creating the resource.  Returns:         A CreateResourceResponse containing a success message and the ID of the         newly created resource.
     * Create Resource
     */
    async silverCreateResourceRaw(requestParameters: SilverCreateResourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateResourceResponse>> {
        if (requestParameters['createResourceRequest'] == null) {
            throw new runtime.RequiredError(
                'createResourceRequest',
                'Required parameter "createResourceRequest" was null or undefined when calling silverCreateResource().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/silver/`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateResourceRequestToJSON(requestParameters['createResourceRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateResourceResponseFromJSON(jsonValue));
    }

    /**
     * Creates a new resource in the layer.  Args:         body: A CreateResourceRequest object containing the name, project ID, and                 optional description for the new resource.         loader: The loader instance to use for creating the resource.  Returns:         A CreateResourceResponse containing a success message and the ID of the         newly created resource.
     * Create Resource
     */
    async silverCreateResource(requestParameters: SilverCreateResourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateResourceResponse> {
        const response = await this.silverCreateResourceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deletes the specified resource.  Args:         resource_id: The ID of the resource to delete.         loader: The loader instance to use for deleting the resource.  Returns:         A MessageResponse indicating the result of the delete operation.
     * Delete Resource
     */
    async silverDeleteResourceRaw(requestParameters: SilverDeleteResourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MessageResponse>> {
        if (requestParameters['resourceId'] == null) {
            throw new runtime.RequiredError(
                'resourceId',
                'Required parameter "resourceId" was null or undefined when calling silverDeleteResource().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/silver/{resource_id}`;
        urlPath = urlPath.replace(`{${"resource_id"}}`, encodeURIComponent(String(requestParameters['resourceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageResponseFromJSON(jsonValue));
    }

    /**
     * Deletes the specified resource.  Args:         resource_id: The ID of the resource to delete.         loader: The loader instance to use for deleting the resource.  Returns:         A MessageResponse indicating the result of the delete operation.
     * Delete Resource
     */
    async silverDeleteResource(requestParameters: SilverDeleteResourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MessageResponse> {
        const response = await this.silverDeleteResourceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Downloads the specified version of the resource as a Parquet file.  Args:         resource_id: The ID of the resource.         version: The version number of the resource.         loader: The loader instance to use for fetching the data.  Returns:         A StreamingResponse containing the Parquet file.
     * Download Version
     */
    async silverDownloadVersionRaw(requestParameters: SilverDownloadVersionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['resourceId'] == null) {
            throw new runtime.RequiredError(
                'resourceId',
                'Required parameter "resourceId" was null or undefined when calling silverDownloadVersion().'
            );
        }

        if (requestParameters['version'] == null) {
            throw new runtime.RequiredError(
                'version',
                'Required parameter "version" was null or undefined when calling silverDownloadVersion().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/silver/{resource_id}/versions/{version}`;
        urlPath = urlPath.replace(`{${"resource_id"}}`, encodeURIComponent(String(requestParameters['resourceId'])));
        urlPath = urlPath.replace(`{${"version"}}`, encodeURIComponent(String(requestParameters['version'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Downloads the specified version of the resource as a Parquet file.  Args:         resource_id: The ID of the resource.         version: The version number of the resource.         loader: The loader instance to use for fetching the data.  Returns:         A StreamingResponse containing the Parquet file.
     * Download Version
     */
    async silverDownloadVersion(requestParameters: SilverDownloadVersionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.silverDownloadVersionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves the metadata of the specified resource.  Args:         resource_id: The ID of the resource to retrieve.         loader: The loader instance to use for fetching the metadata.  Returns:         A MetadataResponse object containing the metadata of the resource.
     * Get Resource
     */
    async silverGetResourceRaw(requestParameters: SilverGetResourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MetadataResponse>> {
        if (requestParameters['resourceId'] == null) {
            throw new runtime.RequiredError(
                'resourceId',
                'Required parameter "resourceId" was null or undefined when calling silverGetResource().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/silver/{resource_id}`;
        urlPath = urlPath.replace(`{${"resource_id"}}`, encodeURIComponent(String(requestParameters['resourceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MetadataResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves the metadata of the specified resource.  Args:         resource_id: The ID of the resource to retrieve.         loader: The loader instance to use for fetching the metadata.  Returns:         A MetadataResponse object containing the metadata of the resource.
     * Get Resource
     */
    async silverGetResource(requestParameters: SilverGetResourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MetadataResponse> {
        const response = await this.silverGetResourceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the schema of the specified version of the resource.  Args:         resource_id: The ID of the resource.         version: The version number of the resource.         loader: The loader instance to use for fetching the data.  Returns:         A SchemaResponse containing the data schema and a sample of the data.
     * Get Schema
     */
    async silverGetSchemaRaw(requestParameters: SilverGetSchemaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SchemaResponse>> {
        if (requestParameters['resourceId'] == null) {
            throw new runtime.RequiredError(
                'resourceId',
                'Required parameter "resourceId" was null or undefined when calling silverGetSchema().'
            );
        }

        if (requestParameters['version'] == null) {
            throw new runtime.RequiredError(
                'version',
                'Required parameter "version" was null or undefined when calling silverGetSchema().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/silver/{resource_id}/versions/{version}/schema`;
        urlPath = urlPath.replace(`{${"resource_id"}}`, encodeURIComponent(String(requestParameters['resourceId'])));
        urlPath = urlPath.replace(`{${"version"}}`, encodeURIComponent(String(requestParameters['version'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SchemaResponseFromJSON(jsonValue));
    }

    /**
     * Returns the schema of the specified version of the resource.  Args:         resource_id: The ID of the resource.         version: The version number of the resource.         loader: The loader instance to use for fetching the data.  Returns:         A SchemaResponse containing the data schema and a sample of the data.
     * Get Schema
     */
    async silverGetSchema(requestParameters: SilverGetSchemaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SchemaResponse> {
        const response = await this.silverGetSchemaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Lists all resources in the layer.  Args:         loader: The loader instance to use for fetching the metadata.  Returns:         A list of MetadataResponse objects containing the metadata of all resources.
     * List Resources
     */
    async silverListResourcesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<MetadataResponse>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/silver/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MetadataResponseFromJSON));
    }

    /**
     * Lists all resources in the layer.  Args:         loader: The loader instance to use for fetching the metadata.  Returns:         A list of MetadataResponse objects containing the metadata of all resources.
     * List Resources
     */
    async silverListResources(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MetadataResponse>> {
        const response = await this.silverListResourcesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Lists all versions of the specified resource along with their lineage information.  Args:         resource_id: The ID of the resource to list versions for.         loader: The loader instance to use for fetching the lineage information.  Returns:         A list of LineageResponse objects representing the versions of the resource.
     * List Versions
     */
    async silverListVersionsRaw(requestParameters: SilverListVersionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<LineageResponse>>> {
        if (requestParameters['resourceId'] == null) {
            throw new runtime.RequiredError(
                'resourceId',
                'Required parameter "resourceId" was null or undefined when calling silverListVersions().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/silver/{resource_id}/versions`;
        urlPath = urlPath.replace(`{${"resource_id"}}`, encodeURIComponent(String(requestParameters['resourceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(LineageResponseFromJSON));
    }

    /**
     * Lists all versions of the specified resource along with their lineage information.  Args:         resource_id: The ID of the resource to list versions for.         loader: The loader instance to use for fetching the lineage information.  Returns:         A list of LineageResponse objects representing the versions of the resource.
     * List Versions
     */
    async silverListVersions(requestParameters: SilverListVersionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<LineageResponse>> {
        const response = await this.silverListVersionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates the metadata of the specified resource.  Args:         resource_id: The ID of the resource to update.         body: An UpdateResourceRequest object containing the new name and                 description for the resource.         loader: The loader instance to use for updating the metadata.  Returns:         A MetadataResponse object containing the updated metadata of the resource.
     * Update Resource
     */
    async silverUpdateResourceRaw(requestParameters: SilverUpdateResourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MetadataResponse>> {
        if (requestParameters['resourceId'] == null) {
            throw new runtime.RequiredError(
                'resourceId',
                'Required parameter "resourceId" was null or undefined when calling silverUpdateResource().'
            );
        }

        if (requestParameters['updateResourceRequest'] == null) {
            throw new runtime.RequiredError(
                'updateResourceRequest',
                'Required parameter "updateResourceRequest" was null or undefined when calling silverUpdateResource().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/silver/{resource_id}`;
        urlPath = urlPath.replace(`{${"resource_id"}}`, encodeURIComponent(String(requestParameters['resourceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateResourceRequestToJSON(requestParameters['updateResourceRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MetadataResponseFromJSON(jsonValue));
    }

    /**
     * Updates the metadata of the specified resource.  Args:         resource_id: The ID of the resource to update.         body: An UpdateResourceRequest object containing the new name and                 description for the resource.         loader: The loader instance to use for updating the metadata.  Returns:         A MetadataResponse object containing the updated metadata of the resource.
     * Update Resource
     */
    async silverUpdateResource(requestParameters: SilverUpdateResourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MetadataResponse> {
        const response = await this.silverUpdateResourceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Uploads a new version of the resource from a Parquet file.  Args:         resource_id: The ID of the resource to upload a new version for.         file: The uploaded Parquet file containing the new version of the data.         loader: The loader instance to use for uploading the data.         from_resource_id: The ID of the existing resource version that this new                 version is derived from.  Returns:         A MessageResponse indicating the result of the upload operation.
     * Upload Version Single
     */
    async silverUploadVersionRaw(requestParameters: SilverUploadVersionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MessageResponse>> {
        if (requestParameters['resourceId'] == null) {
            throw new runtime.RequiredError(
                'resourceId',
                'Required parameter "resourceId" was null or undefined when calling silverUploadVersion().'
            );
        }

        if (requestParameters['fromResourceId'] == null) {
            throw new runtime.RequiredError(
                'fromResourceId',
                'Required parameter "fromResourceId" was null or undefined when calling silverUploadVersion().'
            );
        }

        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling silverUploadVersion().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['fromResourceId'] != null) {
            queryParameters['from_resource_id'] = requestParameters['fromResourceId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }


        let urlPath = `/silver/{resource_id}/versions`;
        urlPath = urlPath.replace(`{${"resource_id"}}`, encodeURIComponent(String(requestParameters['resourceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageResponseFromJSON(jsonValue));
    }

    /**
     * Uploads a new version of the resource from a Parquet file.  Args:         resource_id: The ID of the resource to upload a new version for.         file: The uploaded Parquet file containing the new version of the data.         loader: The loader instance to use for uploading the data.         from_resource_id: The ID of the existing resource version that this new                 version is derived from.  Returns:         A MessageResponse indicating the result of the upload operation.
     * Upload Version Single
     */
    async silverUploadVersion(requestParameters: SilverUploadVersionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MessageResponse> {
        const response = await this.silverUploadVersionRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
