/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateSilverSourceRequest
 */
export interface CreateSilverSourceRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateSilverSourceRequest
     */
    name: string;
}

/**
 * Check if a given object implements the CreateSilverSourceRequest interface.
 */
export function instanceOfCreateSilverSourceRequest(value: object): value is CreateSilverSourceRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateSilverSourceRequestFromJSON(json: any): CreateSilverSourceRequest {
    return CreateSilverSourceRequestFromJSONTyped(json, false);
}

export function CreateSilverSourceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSilverSourceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function CreateSilverSourceRequestToJSON(json: any): CreateSilverSourceRequest {
    return CreateSilverSourceRequestToJSONTyped(json, false);
}

export function CreateSilverSourceRequestToJSONTyped(value?: CreateSilverSourceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

