/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateProjectResponse
 */
export interface CreateProjectResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateProjectResponse
     */
    message: string;
    /**
     * 
     * @type {number}
     * @memberof CreateProjectResponse
     */
    project_id: number;
}

/**
 * Check if a given object implements the CreateProjectResponse interface.
 */
export function instanceOfCreateProjectResponse(value: object): value is CreateProjectResponse {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('project_id' in value) || value['project_id'] === undefined) return false;
    return true;
}

export function CreateProjectResponseFromJSON(json: any): CreateProjectResponse {
    return CreateProjectResponseFromJSONTyped(json, false);
}

export function CreateProjectResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateProjectResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'project_id': json['project_id'],
    };
}

export function CreateProjectResponseToJSON(json: any): CreateProjectResponse {
    return CreateProjectResponseToJSONTyped(json, false);
}

export function CreateProjectResponseToJSONTyped(value?: CreateProjectResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'project_id': value['project_id'],
    };
}

