/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateSilverResourceRequest
 */
export interface CreateSilverResourceRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateSilverResourceRequest
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof CreateSilverResourceRequest
     */
    project_id: number;
    /**
     * 
     * @type {string}
     * @memberof CreateSilverResourceRequest
     */
    description?: string | null;
}

/**
 * Check if a given object implements the CreateSilverResourceRequest interface.
 */
export function instanceOfCreateSilverResourceRequest(value: object): value is CreateSilverResourceRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('project_id' in value) || value['project_id'] === undefined) return false;
    return true;
}

export function CreateSilverResourceRequestFromJSON(json: any): CreateSilverResourceRequest {
    return CreateSilverResourceRequestFromJSONTyped(json, false);
}

export function CreateSilverResourceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSilverResourceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'project_id': json['project_id'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function CreateSilverResourceRequestToJSON(json: any): CreateSilverResourceRequest {
    return CreateSilverResourceRequestToJSONTyped(json, false);
}

export function CreateSilverResourceRequestToJSONTyped(value?: CreateSilverResourceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'project_id': value['project_id'],
        'description': value['description'],
    };
}

