/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateSourceRequest
 */
export interface CreateSourceRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateSourceRequest
     */
    name: string;
}

/**
 * Check if a given object implements the CreateSourceRequest interface.
 */
export function instanceOfCreateSourceRequest(value: object): value is CreateSourceRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateSourceRequestFromJSON(json: any): CreateSourceRequest {
    return CreateSourceRequestFromJSONTyped(json, false);
}

export function CreateSourceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSourceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function CreateSourceRequestToJSON(json: any): CreateSourceRequest {
    return CreateSourceRequestToJSONTyped(json, false);
}

export function CreateSourceRequestToJSONTyped(value?: CreateSourceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

