/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateResourceResponse
 */
export interface CreateResourceResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateResourceResponse
     */
    message: string;
    /**
     * 
     * @type {number}
     * @memberof CreateResourceResponse
     */
    resource_id: number;
}

/**
 * Check if a given object implements the CreateResourceResponse interface.
 */
export function instanceOfCreateResourceResponse(value: object): value is CreateResourceResponse {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('resource_id' in value) || value['resource_id'] === undefined) return false;
    return true;
}

export function CreateResourceResponseFromJSON(json: any): CreateResourceResponse {
    return CreateResourceResponseFromJSONTyped(json, false);
}

export function CreateResourceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateResourceResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'resource_id': json['resource_id'],
    };
}

export function CreateResourceResponseToJSON(json: any): CreateResourceResponse {
    return CreateResourceResponseToJSONTyped(json, false);
}

export function CreateResourceResponseToJSONTyped(value?: CreateResourceResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'resource_id': value['resource_id'],
    };
}

