/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateGoldResourceRequest
 */
export interface CreateGoldResourceRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateGoldResourceRequest
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof CreateGoldResourceRequest
     */
    project_id: number;
    /**
     * 
     * @type {string}
     * @memberof CreateGoldResourceRequest
     */
    description?: string | null;
}

/**
 * Check if a given object implements the CreateGoldResourceRequest interface.
 */
export function instanceOfCreateGoldResourceRequest(value: object): value is CreateGoldResourceRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('project_id' in value) || value['project_id'] === undefined) return false;
    return true;
}

export function CreateGoldResourceRequestFromJSON(json: any): CreateGoldResourceRequest {
    return CreateGoldResourceRequestFromJSONTyped(json, false);
}

export function CreateGoldResourceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateGoldResourceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'project_id': json['project_id'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function CreateGoldResourceRequestToJSON(json: any): CreateGoldResourceRequest {
    return CreateGoldResourceRequestToJSONTyped(json, false);
}

export function CreateGoldResourceRequestToJSONTyped(value?: CreateGoldResourceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'project_id': value['project_id'],
        'description': value['description'],
    };
}

