/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateResourceRequest
 */
export interface CreateResourceRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateResourceRequest
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof CreateResourceRequest
     */
    project_id: number;
    /**
     * 
     * @type {string}
     * @memberof CreateResourceRequest
     */
    description?: string | null;
}

/**
 * Check if a given object implements the CreateResourceRequest interface.
 */
export function instanceOfCreateResourceRequest(value: object): value is CreateResourceRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('project_id' in value) || value['project_id'] === undefined) return false;
    return true;
}

export function CreateResourceRequestFromJSON(json: any): CreateResourceRequest {
    return CreateResourceRequestFromJSONTyped(json, false);
}

export function CreateResourceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateResourceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'project_id': json['project_id'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function CreateResourceRequestToJSON(json: any): CreateResourceRequest {
    return CreateResourceRequestToJSONTyped(json, false);
}

export function CreateResourceRequestToJSONTyped(value?: CreateResourceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'project_id': value['project_id'],
        'description': value['description'],
    };
}

