/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateGoldSourceRequest
 */
export interface CreateGoldSourceRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateGoldSourceRequest
     */
    name: string;
}

/**
 * Check if a given object implements the CreateGoldSourceRequest interface.
 */
export function instanceOfCreateGoldSourceRequest(value: object): value is CreateGoldSourceRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateGoldSourceRequestFromJSON(json: any): CreateGoldSourceRequest {
    return CreateGoldSourceRequestFromJSONTyped(json, false);
}

export function CreateGoldSourceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateGoldSourceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function CreateGoldSourceRequestToJSON(json: any): CreateGoldSourceRequest {
    return CreateGoldSourceRequestToJSONTyped(json, false);
}

export function CreateGoldSourceRequestToJSONTyped(value?: CreateGoldSourceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

