/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DataValueInner
 */
export interface DataValueInner {
}

/**
 * Check if a given object implements the DataValueInner interface.
 */
export function instanceOfDataValueInner(value: object): value is DataValueInner {
    return true;
}

export function DataValueInnerFromJSON(json: any): DataValueInner {
    return DataValueInnerFromJSONTyped(json, false);
}

export function DataValueInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataValueInner {
    return json;
}

export function DataValueInnerToJSON(json: any): DataValueInner {
    return DataValueInnerToJSONTyped(json, false);
}

export function DataValueInnerToJSONTyped(value?: DataValueInner | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

