/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GoldMetadataResponse
 */
export interface GoldMetadataResponse {
    /**
     * 
     * @type {number}
     * @memberof GoldMetadataResponse
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof GoldMetadataResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof GoldMetadataResponse
     */
    description: string | null;
    /**
     * 
     * @type {number}
     * @memberof GoldMetadataResponse
     */
    project_id: number;
    /**
     * 
     * @type {string}
     * @memberof GoldMetadataResponse
     */
    created_at: string;
}

/**
 * Check if a given object implements the GoldMetadataResponse interface.
 */
export function instanceOfGoldMetadataResponse(value: object): value is GoldMetadataResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('project_id' in value) || value['project_id'] === undefined) return false;
    if (!('created_at' in value) || value['created_at'] === undefined) return false;
    return true;
}

export function GoldMetadataResponseFromJSON(json: any): GoldMetadataResponse {
    return GoldMetadataResponseFromJSONTyped(json, false);
}

export function GoldMetadataResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GoldMetadataResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'],
        'project_id': json['project_id'],
        'created_at': json['created_at'],
    };
}

export function GoldMetadataResponseToJSON(json: any): GoldMetadataResponse {
    return GoldMetadataResponseToJSONTyped(json, false);
}

export function GoldMetadataResponseToJSONTyped(value?: GoldMetadataResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'project_id': value['project_id'],
        'created_at': value['created_at'],
    };
}

