/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MetadataResponse
 */
export interface MetadataResponse {
    /**
     * 
     * @type {number}
     * @memberof MetadataResponse
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof MetadataResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof MetadataResponse
     */
    created_at: string;
}

/**
 * Check if a given object implements the MetadataResponse interface.
 */
export function instanceOfMetadataResponse(value: object): value is MetadataResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('created_at' in value) || value['created_at'] === undefined) return false;
    return true;
}

export function MetadataResponseFromJSON(json: any): MetadataResponse {
    return MetadataResponseFromJSONTyped(json, false);
}

export function MetadataResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetadataResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'created_at': json['created_at'],
    };
}

export function MetadataResponseToJSON(json: any): MetadataResponse {
    return MetadataResponseToJSONTyped(json, false);
}

export function MetadataResponseToJSONTyped(value?: MetadataResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'created_at': value['created_at'],
    };
}

