/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DataValueInner } from './DataValueInner';
import {
    DataValueInnerFromJSON,
    DataValueInnerFromJSONTyped,
    DataValueInnerToJSON,
    DataValueInnerToJSONTyped,
} from './DataValueInner';

/**
 * 
 * @export
 * @interface SchemaResponse
 */
export interface SchemaResponse {
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof SchemaResponse
     */
    data_schema: { [key: string]: string; };
    /**
     * 
     * @type {{ [key: string]: Array<DataValueInner>; }}
     * @memberof SchemaResponse
     */
    data: { [key: string]: Array<DataValueInner>; };
}

/**
 * Check if a given object implements the SchemaResponse interface.
 */
export function instanceOfSchemaResponse(value: object): value is SchemaResponse {
    if (!('data_schema' in value) || value['data_schema'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function SchemaResponseFromJSON(json: any): SchemaResponse {
    return SchemaResponseFromJSONTyped(json, false);
}

export function SchemaResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SchemaResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data_schema': json['data_schema'],
        'data': json['data'],
    };
}

export function SchemaResponseToJSON(json: any): SchemaResponse {
    return SchemaResponseToJSONTyped(json, false);
}

export function SchemaResponseToJSONTyped(value?: SchemaResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data_schema': value['data_schema'],
        'data': value['data'],
    };
}

