/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SilverLineageResponse
 */
export interface SilverLineageResponse {
    /**
     * 
     * @type {number}
     * @memberof SilverLineageResponse
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof SilverLineageResponse
     */
    resource_id: number;
    /**
     * 
     * @type {number}
     * @memberof SilverLineageResponse
     */
    delta_version: number;
    /**
     * 
     * @type {number}
     * @memberof SilverLineageResponse
     */
    from_resource_id: number;
    /**
     * 
     * @type {string}
     * @memberof SilverLineageResponse
     */
    created_at: string;
}

/**
 * Check if a given object implements the SilverLineageResponse interface.
 */
export function instanceOfSilverLineageResponse(value: object): value is SilverLineageResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('resource_id' in value) || value['resource_id'] === undefined) return false;
    if (!('delta_version' in value) || value['delta_version'] === undefined) return false;
    if (!('from_resource_id' in value) || value['from_resource_id'] === undefined) return false;
    if (!('created_at' in value) || value['created_at'] === undefined) return false;
    return true;
}

export function SilverLineageResponseFromJSON(json: any): SilverLineageResponse {
    return SilverLineageResponseFromJSONTyped(json, false);
}

export function SilverLineageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SilverLineageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'resource_id': json['resource_id'],
        'delta_version': json['delta_version'],
        'from_resource_id': json['from_resource_id'],
        'created_at': json['created_at'],
    };
}

export function SilverLineageResponseToJSON(json: any): SilverLineageResponse {
    return SilverLineageResponseToJSONTyped(json, false);
}

export function SilverLineageResponseToJSONTyped(value?: SilverLineageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'resource_id': value['resource_id'],
        'delta_version': value['delta_version'],
        'from_resource_id': value['from_resource_id'],
        'created_at': value['created_at'],
    };
}

