/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SilverMetadataResponse
 */
export interface SilverMetadataResponse {
    /**
     * 
     * @type {number}
     * @memberof SilverMetadataResponse
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof SilverMetadataResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof SilverMetadataResponse
     */
    created_at: string;
}

/**
 * Check if a given object implements the SilverMetadataResponse interface.
 */
export function instanceOfSilverMetadataResponse(value: object): value is SilverMetadataResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('created_at' in value) || value['created_at'] === undefined) return false;
    return true;
}

export function SilverMetadataResponseFromJSON(json: any): SilverMetadataResponse {
    return SilverMetadataResponseFromJSONTyped(json, false);
}

export function SilverMetadataResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SilverMetadataResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'created_at': json['created_at'],
    };
}

export function SilverMetadataResponseToJSON(json: any): SilverMetadataResponse {
    return SilverMetadataResponseToJSONTyped(json, false);
}

export function SilverMetadataResponseToJSONTyped(value?: SilverMetadataResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'created_at': value['created_at'],
    };
}

