/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateGoldSourceRequest
 */
export interface UpdateGoldSourceRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateGoldSourceRequest
     */
    name: string;
}

/**
 * Check if a given object implements the UpdateGoldSourceRequest interface.
 */
export function instanceOfUpdateGoldSourceRequest(value: object): value is UpdateGoldSourceRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function UpdateGoldSourceRequestFromJSON(json: any): UpdateGoldSourceRequest {
    return UpdateGoldSourceRequestFromJSONTyped(json, false);
}

export function UpdateGoldSourceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateGoldSourceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function UpdateGoldSourceRequestToJSON(json: any): UpdateGoldSourceRequest {
    return UpdateGoldSourceRequestToJSONTyped(json, false);
}

export function UpdateGoldSourceRequestToJSONTyped(value?: UpdateGoldSourceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

