/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateResourceRequest
 */
export interface UpdateResourceRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateResourceRequest
     */
    name: string;
}

/**
 * Check if a given object implements the UpdateResourceRequest interface.
 */
export function instanceOfUpdateResourceRequest(value: object): value is UpdateResourceRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function UpdateResourceRequestFromJSON(json: any): UpdateResourceRequest {
    return UpdateResourceRequestFromJSONTyped(json, false);
}

export function UpdateResourceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateResourceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function UpdateResourceRequestToJSON(json: any): UpdateResourceRequest {
    return UpdateResourceRequestToJSONTyped(json, false);
}

export function UpdateResourceRequestToJSONTyped(value?: UpdateResourceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

