/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateGoldResourceRequest
 */
export interface UpdateGoldResourceRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateGoldResourceRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateGoldResourceRequest
     */
    description?: string | null;
}

/**
 * Check if a given object implements the UpdateGoldResourceRequest interface.
 */
export function instanceOfUpdateGoldResourceRequest(value: object): value is UpdateGoldResourceRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function UpdateGoldResourceRequestFromJSON(json: any): UpdateGoldResourceRequest {
    return UpdateGoldResourceRequestFromJSONTyped(json, false);
}

export function UpdateGoldResourceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateGoldResourceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function UpdateGoldResourceRequestToJSON(json: any): UpdateGoldResourceRequest {
    return UpdateGoldResourceRequestToJSONTyped(json, false);
}

export function UpdateGoldResourceRequestToJSONTyped(value?: UpdateGoldResourceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
    };
}

