/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateSilverResourceRequest
 */
export interface UpdateSilverResourceRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateSilverResourceRequest
     */
    name: string;
}

/**
 * Check if a given object implements the UpdateSilverResourceRequest interface.
 */
export function instanceOfUpdateSilverResourceRequest(value: object): value is UpdateSilverResourceRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function UpdateSilverResourceRequestFromJSON(json: any): UpdateSilverResourceRequest {
    return UpdateSilverResourceRequestFromJSONTyped(json, false);
}

export function UpdateSilverResourceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateSilverResourceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function UpdateSilverResourceRequestToJSON(json: any): UpdateSilverResourceRequest {
    return UpdateSilverResourceRequestToJSONTyped(json, false);
}

export function UpdateSilverResourceRequestToJSONTyped(value?: UpdateSilverResourceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

