/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateSilverSourceRequest
 */
export interface UpdateSilverSourceRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateSilverSourceRequest
     */
    name: string;
}

/**
 * Check if a given object implements the UpdateSilverSourceRequest interface.
 */
export function instanceOfUpdateSilverSourceRequest(value: object): value is UpdateSilverSourceRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function UpdateSilverSourceRequestFromJSON(json: any): UpdateSilverSourceRequest {
    return UpdateSilverSourceRequestFromJSONTyped(json, false);
}

export function UpdateSilverSourceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateSilverSourceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function UpdateSilverSourceRequestToJSON(json: any): UpdateSilverSourceRequest {
    return UpdateSilverSourceRequestToJSONTyped(json, false);
}

export function UpdateSilverSourceRequestToJSONTyped(value?: UpdateSilverSourceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

