/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateSourceRequest
 */
export interface UpdateSourceRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateSourceRequest
     */
    name: string;
}

/**
 * Check if a given object implements the UpdateSourceRequest interface.
 */
export function instanceOfUpdateSourceRequest(value: object): value is UpdateSourceRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function UpdateSourceRequestFromJSON(json: any): UpdateSourceRequest {
    return UpdateSourceRequestFromJSONTyped(json, false);
}

export function UpdateSourceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateSourceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function UpdateSourceRequestToJSON(json: any): UpdateSourceRequest {
    return UpdateSourceRequestToJSONTyped(json, false);
}

export function UpdateSourceRequestToJSONTyped(value?: UpdateSourceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

