/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VersionResponse
 */
export interface VersionResponse {
    /**
     * 
     * @type {number}
     * @memberof VersionResponse
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof VersionResponse
     */
    resource_id: number;
    /**
     * 
     * @type {number}
     * @memberof VersionResponse
     */
    version: number;
    /**
     * 
     * @type {string}
     * @memberof VersionResponse
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof VersionResponse
     */
    s3_key: string;
    /**
     * 
     * @type {string}
     * @memberof VersionResponse
     */
    created_at: string;
    /**
     * 
     * @type {string}
     * @memberof VersionResponse
     */
    updated_at: string;
}

/**
 * Check if a given object implements the VersionResponse interface.
 */
export function instanceOfVersionResponse(value: object): value is VersionResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('resource_id' in value) || value['resource_id'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('s3_key' in value) || value['s3_key'] === undefined) return false;
    if (!('created_at' in value) || value['created_at'] === undefined) return false;
    if (!('updated_at' in value) || value['updated_at'] === undefined) return false;
    return true;
}

export function VersionResponseFromJSON(json: any): VersionResponse {
    return VersionResponseFromJSONTyped(json, false);
}

export function VersionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'resource_id': json['resource_id'],
        'version': json['version'],
        'status': json['status'],
        's3_key': json['s3_key'],
        'created_at': json['created_at'],
        'updated_at': json['updated_at'],
    };
}

export function VersionResponseToJSON(json: any): VersionResponse {
    return VersionResponseToJSONTyped(json, false);
}

export function VersionResponseToJSONTyped(value?: VersionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'resource_id': value['resource_id'],
        'version': value['version'],
        'status': value['status'],
        's3_key': value['s3_key'],
        'created_at': value['created_at'],
        'updated_at': value['updated_at'],
    };
}

